# AOS 51 Lab, Spring 2018, Lab #3

Topics covered in Lab #3:
* 2-dimensional array creation, manipulation, and statistics using numpy
---

# Creating 2D ararys

Last lecture introduced arrays in the `numpy` module, but we only worked with 1D data sets. 

This lecture will focus on 2-dimensional arrays, and subsequent lectures will extend our skills to 3- and 4-dimensional data. 

We still need to import numpy at the top of the script and execute this cell.

In [1]:
import numpy as np

Recall from last lecture that we created 1D arrays using, for example:

In [2]:
arr_1d = np.array([1,2,3,4])

A second dimension is added by a new list of values, separating the lists by a comma, and then a final set of square brackets around the lists:

In [3]:
arr_2d = np.array([[1,2,3,4], [5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


Printing the array show us its dimensions: `arr_2d` has 2 rows and 4 columns or is a (2 x 4) array of [rows x columns].

Let's use `np.shape()` to confirm:

In [4]:
print(np.shape(arr_2d))

(2, 4)


So, the ** 1st dimension is rows ** and the ** 2nd dimension is columns **, or in tabular form:

| |Col 0|Col 1|Col 2| Col 3|
|---|---|---|---|
|**Row 0**| 1 | 2 | 3 | 4 |
|**Row 1**| 5 | 6 | 7 | 8 |

** REMEMBER - Python always begins counting with 0, not 1. This includes dimension indices.**

** Numpy refers to a dimension index as an "[axis](https://docs.scipy.org/doc/numpy-1.13.0/glossary.html)". ** 

** So a 2D array has an axis of 0 (1st dimension) and an axis of 1 (2nd dimension). **

Optional further reading:

[Why programmers start counting at zero](https://skillcrush.com/2013/01/17/why-programmers-start-counting-at-zero/)

---
# 2D slicing

We saw that slicing lists and 1D arrays took the form of, for example:

`janjune_2017 = temp_2017[0:6] #extract items from index 0 through 5`

The same slicing syntax applies for multi-dimensional arrays, we just need to include slicing commands for each dimension in the array.

Let's stick with `arr_2d` defined above and demonstrate examples of 2D slicing. 


* Slicing items in dimension 1 (axis 0) and dimension 2 (axis 1) from the start through end-1 indices:

   `arr_2d[start:end,start:end]`

* Slicing items in dimension 1 and 2 from the start to final indices:

   `arr_2d[start:,start:]`       

* Slicing items in dimension 1 and from the from the zeroth through end-1 indices:

   `arr_2d[:end,:end]`            

* Copy of the whole 2D array (i.e. slice all values in dimensions 1 and 2)

   `arr_2d[:,:]`     

Of course, you can mix and match these slicing commands for dimensions. For example:

* Slicing items in dim. 1 start through end-1 indices, and for all indices in dim. 2

   `arr_2d[start:end,:]`
   
Let's see these slicing commands in action:

In [14]:
# Slice the entire 2D array, [all indices in dimension 1 (rows), all indices in dimension 2 (columns)]
print(arr_2d[:,:])

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
# Slice the entire first row [zeroth index dim 1, all indices dim 2]
print(arr_2d[0,:])

[1 2 3 4]


In [16]:
# Slice the entire second row [1st index dim 1, all indices dim 2]
print(arr_2d[1,:])

[5 6 7 8]


In [17]:
# Slicing the entire first column [all indices dim 1, zeroth index dim 2]
print(arr_2d[:,0])

[1 5]


In [18]:
# Slice the 3rd column [all indices dim 1, 2nd index dim 2]
print(arr_2d[:,2])

[3 7]


In [19]:
# Slicing the value in the 1st row and 1st column [zeroth index dim 1, zeroth index dim 2]
print(arr_2d[0,0])

1


In [20]:
# Slicing the value in 2nd row and 2nd column [1st index dim 1, 1st index for dim 2]
print(arr_2d[1,1])

6


In [21]:
# Slicing the values in rows 1-2 and columns 1-2 [zeroth through 1st index dim 1, zeroth through 1st index dim 2]
print(arr_2d[0:2,0:2])

[[1 2]
 [5 6]]


In [22]:
# Slicing the values in row 2, columns 3-4 [1st index dim 1, 2nd through 3rd index dim 2]
print(arr_2d[1,2:4])

[7 8]


** In-lab exercise **

Here are 9am-noon temperatures (degrees F) in downtown LA on April 16 and April 17, 2018:

| |9am | 10am | 11am | noon |
|---|---|---|---|---|
|**April 17**|59.0|64.9|66.0|69.0|
|**April 16**|61.0|64.0|63.0|63.0|


Or in table-index form:

| |Col 0 | Col 1 | Col 2 | Col 3 |
|---|---|---|---|---|
|**Row 0**|59.0|64.9|66.0|69.0|
|**Row 1**|61.0|64.0|63.0|63.0|

1. Store this data in a new 2D array, with shape [2 x 4], and call it `temp`. 
2. What is the slicing command to extract the temperature at 10am on April 16?
3. What is the slicing command to extract the 9am-11am temperatures on April 17?

---
# Another way to create 2D arrays

Oftentimes we want to create 2D arrays from two pieces of 1D data. 

For instance, here are the last 10 years of average annual temperature (degrees F) over Los Angeles and San Francisco.

|City|2008|2009|2010|2011|2012|2013|2014|2015|2016|2017|
|---|---|---|---|---|---|---|---|---|---|---|---|
|LA|63.7|62.7|61.9|61.8|63.4|63.7|66.0|65.6|64.8|65.1|
|SF|57.6|58.1|58.6|56.9|57.6|58.0|62.0|60.4|59.7|59.9|

Don't worry, I won't make you enter these values into an array :). 

Rather, we'll use numpy's stacking functions to quickly merge two 1D arrays into one 2D array:

   * Vertical, i.e. concatenation along the rows, using [np.vstack()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.vstack.html)
   * Horizontally, i.e. or concatenation along the columns, using [np.hstack()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.hstack.html) 
   

In [ ]:
la_temp = np.array([63.7, 62.7, 61.9, 61.8, 63.4, 63.7, 66.0, 65.6, 64.8, 65.1])
sf_temp = np.array([57.6, 58.1, 58.6, 56.9, 57.6, 58.0, 62.0, 60.4, 59.7, 59.9])

# Stack vertically (concatenate along the rows)
print(np.vstack((la_temp,sf_temp)))
x = np.vstack((la_temp,sf_temp))
print(x)

In [15]:
# Stack horizontally (concatenate along the columns)
print(np.hstack((la_temp,sf_temp)))

[ 63.7  62.7  61.9  61.8  63.4  63.7  66.   65.6  64.8  65.1  57.6  58.1
  58.6  56.9  57.6  58.   62.   60.4  59.7  59.9]


** In-class exercise **

Use code to determine the shapes of the vertically and horizontally stacked arrays above.

---
# Arithmetic on 2D arrays

Arithmetic on 2D arrays is the same as on 1D arrays, but now we need to specific the axis (dimension index) to perform the arithmetic on. 

Let's demonstrate some examples using the 2008-2017 LA and SF temperature array above.

In [16]:
# Create a 2x10 array using vstack
la_sf_temp = np.vstack((la_temp,sf_temp))
print(np.shape(la_sf_temp))

(2, 10)


We have a [2 x 10] array where ** dimension 1 (axis 0) is the number of cities ** and ** dimension 2 (axis 1) the number of years.**

Let's compute the mean temperature for each city (i.e. across dimension/axis 1): 

In [17]:
avg_temp = np.mean(la_sf_temp, axis=1)
print(avg_temp)

[ 63.87  58.88]


Keeping track of Python's indexing can be tricky. Starting a count with zero is not natural for humans! 

What happens if we forget that counting begins at zero and we try to take the mean over the 2nd axis in Python-land?

In [18]:
avg_temp = np.mean(la_sf_temp, axis=2)
print(avg_temp)

IndexError: tuple index out of range

Python raises an `IndexError`, points us to the offending line at the very top of the message, and tells us that the index is out of range. Axis=2 is out of range because we only have axes of 0 (cities) and 1 (years) in Python-land.

For completeness, what happens if we instead take the mean over `axis=0`?

In [ ]:
print(np.mean(la_sf_temp, axis=0))

We'll simply obtain a 1D array (of length 10) containing the average LA/SF temperatures for each year during 2008-2017.

Performing other statistics (e.g., `np.sum()`, `np.std()`, etc.) on 2D arrays has the exact same syntax as above - just tell Python which axis to perform the statistic over. 

** In-lab exercise **

Below are two 1D arrays storing the last 10 years (2008-2017) of annual precipitation totals (unit: inches) over Fresno and San Diego. 

1. Using `np.vstack`, create a new 2D [2 x 10] array called `fr_sd_precip`.
2. Using `np.mean`, compute the 2008-2017 average precipitation for Fresno and San Diego? 
3. Based on the results from (2), which city was wetter?
4. Using `np.sum`, how much rainfall accumulated during 2008-2017 for each city? 

In [26]:
fr_precip = np.array([8.48, 9.08, 16.54, 10.93, 9.99, 3.02, 7.47, 9.00, 13.67, 13.20])
sd_precip = np.array([11.11, 5.5, 16.29, 9.09, 6.64, 5.58, 7.79, 9.92, 10.23, 7.93])

### Spatial averaging in 2D arrays

2D climate datasets often represent some variable over a latitude x longitude grid. Latitude is the 1st dimension, longitude is the 2nd dimension. 

For example, here is a sample of values over a 3 x 3 (rows x columns = lat x lon) series of grid cells:

|  |Lon 0|Lon 1|Lon 2
|---|---|---|
|**Lat 0**| 73 | 71 | 74 |
|**Lat 1**| 72 | 73 | 75 |
|**Lat 2**| 70 | 69 | 68 |

** Note: for this array, latitude  = axis 0 and longitude  = axis 1. **

Let's learn 3 spatial averaging techniques: 

1. Zonal averages (or averages across all longitudes for a given latitude)
2. Meridional averages (or averages across all latitudes for a given longitude)
3. Average across all grid cells ("domain-average")

First, let's create a 3 x 3 numpy array:

In [ ]:
# 2D [3 x 3] array of temperatures 
temp_2d = np.array([[73, 71, 74], [72,73,75], [70,69,68]])
print(temp_2d)

** 1. Zonal averages **

In [ ]:
# 1. Zonal average 
# Average across longitudes for each latitude. 
# In temp_2d, longitude is dimension 2/axis 1 in Python-land. 
zonal_avg = np.mean(temp_2d, axis=1)
print(zonal_avg)

** 2. Meridional averages **

In [ ]:
# 2. Meridional average
# Average across latitudes for each longitude. Latitude is dimension/axis 0 in Python-land. 
# In temp_2d, latitude is dimension 1/axis 0 in Python-land. 
meridional_avg = np.mean(temp_2d, axis=0) 
print(meridional_avg)

** 3. Domain-average (across all latitudes and longitudes) **

There are a couple ways to do this, but simplest is a two-step process:

1. Collapse the 2D array to 1D using a special property of arrays called  [flatten()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flatten.html) 
   * By collapse, I mean rearange the 2D array so that it no longer has two dimensions, only a single dimension containing all of the values. 
2. Use the regular `np.mean()` function to compute the average

Step 1: Flatten the 2D array to form a 1D array

In [ ]:
temp_1d = temp_2d.flatten()
print(temp_1d)

Step 2. Using the usual `np.mean` function over the 1D array. We don't need to specify an axis anymore, since only one dimension exists (though, you could add `axis=0`). 

In [ ]:
domain_avg = np.mean(temp_1d)
print(domain_avg)

** In-class exercise **

Below is a 5x5 array storing future temperature changes (degrees C) for 25 grid cells in California compared to today's conditions. This data comes from the [CCSM4 global climate model](http://www.cesm.ucar.edu/models/ccsm4.0/) and assumes that [greenhouse gases continue to steadily rise in the 21st century](https://www.climatechangeinaustralia.gov.au/en/climate-campus/modelling-and-projections/projecting-future-climate/greenhouse-gas-scenarios/). 

| | Lon 0 | Lon 1 | Lon 2 | Lon 3 | Lon 4|
|---|---|---|---|---|---|
|**Lat 0**| 1.9 | 1.7 | 1.6 | 1.7 | 2.0 |
|**Lat 1**| 1.8 | 1.7 | 1.6 | 2.2 | 2.5 |
|**Lat 2**| 1.7 | 1.7 | 2.1 | 2.5 | 2.3 |
|**Lat 3**| 1.5 | 1.5 | 1.7 | 2.0 | 2.0 |
|**Lat 4**| 1.5 | 1.5 | 1.7 | 2.0 | 1.9 |

Here is the data as a numpy array:

In [ ]:
ccsm4_temp_change = np.array([
                            [1.9, 1.7, 1.6, 1.7, 2.0],
                            [1.8, 1.7, 1.6, 2.2, 2.5],
                            [1.7, 1.7, 2.1, 2.5, 2.3],
                            [1.5, 1.5, 1.7, 2.0, 2.0],
                            [1.5, 1.5, 1.7, 2.0, 1.9]])

1. What is the domain-average temperature change?
   - 1a) Use np.flatten() to collapse the 2D array into a 1D array
   - 1b) Use np.mean() to compute the average

---
# Iterating over arrays

Oftentimes, we need to iterate over elements in a 2D array, like `temp_2d`. 

Recall from Lab #1 that we could iterate over a 1D list or array (like `temp_1d`) with:

In [ ]:
for t in temp_1d:
    print(t)

Iterating over 2D arrays is similar, but with two differences:

1. We need to have two for loops - one for each dimension.
2. We will iterate over the **indices** of each dimension, rather than items in a dimension. 

Let's go through the process step-by-step:

** Step 1: Gather dimension sizes in the 2D array using np.shape **

In [ ]:
# Size of latitude ("nlat") and longitude ("nlon") dimensions in temp_2d 
nlat, nlon = np.shape(temp_2d)
print(nlat, nlon)

Each dimension has a size of 3.

** Step 2: Create a range of numbers in each dimension size using np.arange **

Since we're looping over *indices*, let's create some index ranges for lat/lon:

In [ ]:
lat_indices = np.arange(0,nlat)
print(lat_indices)

In [ ]:
lon_indices = np.arange(0,nlon)
print(lon_indices)

So, we'll loop through indices 0, 1 and 2 over the latitude and longitude dimensions.

** Step 3: Loop over the lat indices and then the lon indices **

In [ ]:
for y in lat_indices:
    for x in lon_indices:
        print(temp_2d[y,x])

Same output as when we looped over `temp_1d`. 

Let's use some [fancy printing](https://pyformat.info/) to help us better understand what the `temp_2d[y,x]` slice is doing:

In [ ]:
for y in lat_indices:
    for x in lon_indices:
        print('Lat idx = {0}, lon idx = {1}, temp = {2}'.format(y, x, temp_2d[y,x]))

Note how the inner loop (over `lon_indices`) completes itself before returning to the next iteration in the outer loop (over `lat_indices`). 

---
# Lists, Arrays, Loops, and If Statements!

Now that we can iterate over 2D arrays, we can apply knowledge from lab #1 to use lists, arrays, for loops, and if statements to do interesting 2D analyses. 

Let's work with `ccsm4_temp_change` and answer the question:
> How many grid cells experience warming of at least 2 degrees C?

Recall that `ccsm4_temp_change` is the following:

In [ ]:
print(ccsm4_temp_change)

Create a new cell below and code through the following steps:
1. Compute the length of each dimension in `ccsm4_temp_change` using `np.shape`
2. Create new ranges of the indices in the lat/lon dimensins of `ccsm4_temp_change`
   * Let's call these ranges "ccsm4_lat_indices" and "ccsm4_lon_indices"
3. Create an empty list called "high_warming_cells" to store changes >= 2 degrees C
4. Now we'll loop over the lat/lon indices and append values of at least 2 deg C
5. Count the number of items in "high_warming_cells" using the len() function. 